services:
  client:
    build: .
    ports:
      - "5173:5173"
      - "9002:9000"
    volumes:
      - ./:/var/pdf2odt
    working_dir: /var/pdf2odt
    command: ["./startservices.sh"]
    networks:
      - webappnetwork

networks:
  webappnetwork:
    driver: bridge
